# Generated by Django 5.2.7 on 2025-11-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawLineData',
            fields=[
                ('id', models.BigAutoField(db_column='_id', primary_key=True, serialize=False)),
                ('machine_id', models.CharField(blank=True, db_column='MachineID', max_length=8, null=True)),
                ('recipe_code', models.CharField(blank=True, db_column='RecipeCode', max_length=50, null=True)),
                ('line_speed_actual', models.FloatField(blank=True, db_column='LineSpeedActual', null=True)),
                ('line_speed_set', models.FloatField(blank=True, db_column='LineSpeedSet', null=True)),
                ('timestamp', models.DateTimeField(db_column='TimeStamp')),
                ('date_created', models.DateTimeField(db_column='DateCreated')),
                ('processed_flag', models.BooleanField(db_column='ProcessedFlag', default=False)),
            ],
            options={
                'db_table': 'FRC',
                'ordering': ['timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeoverSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.FloatField(unique=True)),
                ('recipe_change_time', models.DateTimeField(blank=True, null=True)),
                ('current_recipe', models.TextField(blank=True, null=True)),
                ('previous_recipe', models.TextField(blank=True, null=True)),
                ('ramp_down_timestamp', models.DateTimeField(blank=True, db_column='ramp_down', null=True)),
                ('setup_start_timestamp', models.DateTimeField(blank=True, db_column='setup_start', null=True)),
                ('ramp_up_timestamp', models.DateTimeField(blank=True, db_column='ramp_up', null=True)),
                ('setup_complete_timestamp', models.DateTimeField(blank=True, db_column='setup_complete', null=True)),
                ('ramp_up_time_loss', models.FloatField(blank=True, null=True)),
                ('ramp_down_time_loss', models.FloatField(blank=True, null=True)),
                ('setup_time_actual', models.FloatField(blank=True, db_column='setup_time_act', null=True)),
                ('standard_time', models.BigIntegerField(blank=True, null=True)),
                ('static_setup_time', models.FloatField(blank=True, null=True)),
                ('ramp_up_time', models.FloatField(blank=True, null=True)),
                ('current_type', models.TextField(blank=True, null=True)),
                ('previous_type', models.TextField(blank=True, null=True)),
                ('change_over_type', models.TextField(blank=True, db_column='change_over', null=True)),
                ('overshoot_category', models.CharField(blank=True, choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Operational', 'Operational'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=50, null=True)),
                ('overshoot_reason', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'ChangeoverSummary',
                'ordering': ['-recipe_change_time'],
            },
        ),
        migrations.CreateModel(
            name='RecipeMaster',
            fields=[
                ('recipe_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('target_speed', models.FloatField()),
                ('recipe_type', models.CharField(help_text="e.g., 'Steel' or 'Fabric'", max_length=50)),
            ],
            options={
                'db_table': 'RecipeMaster',
            },
        ),
    ]
