# Generated by Django 5.2.7 on 2025-12-15 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeoverCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_category', models.CharField(blank=True, max_length=50, null=True)),
                ('old_reason', models.TextField(blank=True, null=True)),
                ('new_category', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Operational', 'Operational'), ('Other', 'Other'), ('None', 'None')], max_length=50)),
                ('new_reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changeover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='data_processor.changeoversummary')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ChangeoverCorrectionRequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
