# Generated by Django 6.0 on 2026-04-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0002_changeovercorrectionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardTimeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeover_key', models.CharField(help_text="e.g., 'Steel to Steel'", max_length=100, unique=True)),
                ('standard_time', models.FloatField()),
            ],
            options={
                'db_table': 'StandardTimeMaster',
            },
        ),
    ]
