# Generated by Django 6.0 on 2026-04-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0003_standardtimemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeovercorrectionrequest',
            name='new_category',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Operational', 'Operational'), ('Material', 'Material'), ('Other', 'Other'), ('None', 'None')], max_length=50),
        ),
        migrations.AlterField(
            model_name='changeoversummary',
            name='overshoot_category',
            field=models.CharField(blank=True, choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Operational', 'Operational'), ('Material', 'Material'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=50, null=True),
        ),
    ]
