# Generated by Django 6.0 on 2026-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0004_alter_changeovercorrectionrequest_new_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeoversummary',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeoversummary',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeoversummary',
            name='shift',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
