# Generated by Django 6.0 on 2026-04-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0005_changeoversummary_production_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('recipe_code', models.CharField(db_column='recipe_code', max_length=100, primary_key=True, serialize=False)),
                ('sap_code', models.CharField(blank=True, db_column='sap_code', max_length=100, null=True)),
            ],
            options={
                'db_table': 'MaterialMaster',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='recipemaster',
            name='sap_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
