# Generated by Django 6.0 on 2026-04-24 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0006_materialmaster_recipemaster_sap_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvershootReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='changeovercorrectionrequest',
            name='new_category',
        ),
        migrations.RemoveField(
            model_name='changeovercorrectionrequest',
            name='new_reason',
        ),
        migrations.RemoveField(
            model_name='changeovercorrectionrequest',
            name='old_category',
        ),
        migrations.RemoveField(
            model_name='changeovercorrectionrequest',
            name='old_reason',
        ),
        migrations.RemoveField(
            model_name='changeoversummary',
            name='overshoot_category',
        ),
        migrations.RemoveField(
            model_name='changeoversummary',
            name='overshoot_reason',
        ),
        migrations.AddField(
            model_name='changeovercorrectionrequest',
            name='new_overshoot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_correction_requests', to='data_processor.overshootreasons'),
        ),
        migrations.AddField(
            model_name='changeovercorrectionrequest',
            name='old_overshoot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_correction_requests', to='data_processor.overshootreasons'),
        ),
        migrations.AddField(
            model_name='changeoversummary',
            name='overshoot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_processor.overshootreasons'),
        ),
    ]
